# Clock
set_property PACKAGE_PIN W5 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Button
set_property PACKAGE_PIN U18 [get_ports btn_c]						
set_property IOSTANDARD LVCMOS33 [get_ports btn_c]
set_property PACKAGE_PIN T18 [get_ports btn_r]						
set_property IOSTANDARD LVCMOS33 [get_ports btn_r]

# VGA Connector
set_property PACKAGE_PIN G19 [get_ports vga_red_0]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_red_0]
set_property PACKAGE_PIN H19 [get_ports vga_red_1]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_red_1]
set_property PACKAGE_PIN J19 [get_ports vga_red_2]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_red_2]
set_property PACKAGE_PIN N19 [get_ports vga_red_3]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_red_3]
set_property PACKAGE_PIN N18 [get_ports vga_blue_0]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_blue_0]
set_property PACKAGE_PIN L18 [get_ports vga_blue_1]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_blue_1]
set_property PACKAGE_PIN K18 [get_ports vga_blue_2]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_blue_2]
set_property PACKAGE_PIN J18 [get_ports vga_blue_3]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_blue_3]
set_property PACKAGE_PIN J17 [get_ports vga_green_0]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_green_0]
set_property PACKAGE_PIN H17 [get_ports vga_green_1]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_green_1]
set_property PACKAGE_PIN G17 [get_ports vga_green_2]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_green_2]
set_property PACKAGE_PIN D17 [get_ports vga_green_3]				
set_property IOSTANDARD LVCMOS33 [get_ports vga_green_3]
set_property PACKAGE_PIN P19 [get_ports h_sync]						
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]						
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]

# UART
set_property PACKAGE_PIN A18 [get_ports rs_tx]						
set_property IOSTANDARD LVCMOS33 [get_ports rs_tx]
set_property PACKAGE_PIN B18 [get_ports rs_rx]						
set_property IOSTANDARD LVCMOS33 [get_ports rs_rx]

# LED
set_property PACKAGE_PIN U16 [get_ports led0]					
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property PACKAGE_PIN E19 [get_ports led1]					
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property PACKAGE_PIN U19 [get_ports led2]					
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN V19 [get_ports led3]					
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property PACKAGE_PIN W18 [get_ports led4]					
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property PACKAGE_PIN U15 [get_ports led5]					
set_property IOSTANDARD LVCMOS33 [get_ports led5]
set_property PACKAGE_PIN U14 [get_ports led6]					
set_property IOSTANDARD LVCMOS33 [get_ports led6]
set_property PACKAGE_PIN V14 [get_ports led7]					
set_property IOSTANDARD LVCMOS33 [get_ports led7]
set_property PACKAGE_PIN V13 [get_ports led8]					
set_property IOSTANDARD LVCMOS33 [get_ports led8]
set_property PACKAGE_PIN V3 [get_ports led9]					
set_property IOSTANDARD LVCMOS33 [get_ports led9]
set_property PACKAGE_PIN W3 [get_ports led10]					
set_property IOSTANDARD LVCMOS33 [get_ports led10]
set_property PACKAGE_PIN U3 [get_ports led11]					
set_property IOSTANDARD LVCMOS33 [get_ports led11]
set_property PACKAGE_PIN P3 [get_ports led12]					
set_property IOSTANDARD LVCMOS33 [get_ports led12]
set_property PACKAGE_PIN N3 [get_ports led13]					
set_property IOSTANDARD LVCMOS33 [get_ports led13]
set_property PACKAGE_PIN P1 [get_ports led14]					
set_property IOSTANDARD LVCMOS33 [get_ports led14]
set_property PACKAGE_PIN L1 [get_ports led15]					
set_property IOSTANDARD LVCMOS33 [get_ports led15]
